apiVersion: v1
kind: Service
metadata:
  name: meetup-app
  labels:
    app: meetup-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 32000
      name: meetup-app
  selector:
    app: meetup-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetup-app
  labels:
    app: meetup-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meetup-app
  template:
    metadata:
      labels:
        app: meetup-app
    spec:
      containers:
      - name: meetup-app
        image: docker.io/test/meetup-app
        ports:
        - containerPort: 8080
        env:
        - name: SIMPLE_MSG
          value: Hello Meetup#5 from the sample app!
        imagePullPolicy: Always
