apiVersion: v1
kind: Service
metadata:
  name: app-web
  labels:
    app: app-web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: app-web
  selector:
    app: app-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-web
  labels:
    app: app-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-web
  template:
    metadata:
      labels:
        app: app-web
    spec:
      containers:
      - name: app-web
        image: docker.io/test/app-from-source
        ports:
        - containerPort: 8080
